# Generated by Django 6.0.1 on 2026-02-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add book'), ('can_change_book', 'Can change book'), ('can_delete_book', 'Can delete book'), ('can_view_book', 'Can view book details')]},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_manage_users', 'Can manage users')]},
        ),
    ]
